SRCS		=	Sed.cpp.main.cpp
OBJS		=	$(SRCS:.cpp=.o)

COMPILER	=	clang++
RM		=	rm.-rf
COMPILE_FLAG	=	-Wall.-Werror.-Wextra.-I./

NAME		=	replace

all:		$(NAME)

$(NAME):	$(OBJS)
			$(COMPILER).$(COMPILE_FLAG).-o.$(NAME).$(OBJS)

clean:
			$(RM).$(OBJS)

fclean:		clean
			$(RM).$(NAME)

re:		fclean.$(NAME)

test:		$(NAME)
			./replace.Makefile."."."."
			./replace.tests/1."kchoi"."42seoul"
			./replace.tests/2."test"."work"

.PHONY:		all.clean.fclean.re.test
